"""empty message

Revision ID: b01f93be1d9c
Revises: fa43d6d9b3d9
Create Date: 2020-06-29 14:45:57.443392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01f93be1d9c'
down_revision = 'fa43d6d9b3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'number')
    # ### end Alembic commands ###
